### ISSUE TITLE
Support pandoc

### ISSUE THREAD

**Issue by fizruk** [sharelatex/clsi-sharelatex#18]
I'm not sure I'm creating issue in a relevant repo, please move it if necessary.

I just came across the wonderful ShareLatex and I would like to use it with some of my projects. However, I do not use pure LaTeX, but instead have a `.tex` template and a few Pandoc Markdown files to build with [`pandoc`](http://johnmacfarlane.net/pandoc/).

An example of such a project is available in [this repo](https://github.com/fizruk/haskell-2015). Although it's in Russian, you can see that PDF can be constructed with a single `pandoc` command.

Another example is [this CV template](https://github.com/fizruk/cv-template) (it's documented in English).

I find `pandoc` very useful since source code becomes much cleaner and easier to maintain.
It also provides ways to render output in many other formats (which could also be a nice ShareLatex feature on its own).

It would be very nice if ShareLatex could provide `pandoc` compiler!

I understand that my request may not be compatible with ShareLatex's idea and perhaps I just want a different service (SharePandoc?).

**Comment by jpallen** [comment]
We've considered this (and even had some prototype code working), but unfortunately it proved to be too complicated a feature for the minimal use it would likely get at ShareLaTeX. Like you say, we have a focus on LaTeX mainly, sorry.

**Comment by slevey087** [comment]
Can we revive this request?

Really what I'd like to be able to do is use Markdown and AsciiMath instead of LaTeX, but using the Overleaf interface. But since Pandoc allows me to use Markdown and AsciiMath, I'd settle for Pandoc!
